### ISSUE TITLE
[CRITICAL] Artifacts

### ISSUE THREAD

**Issue by Anthony01M** [Berry-Studios/BerryPteroEgg#1]
It appears that the artifacts gets deleted each month, making it sending that the artifact is not found or access denied.
`{"message":"Artifact not found or access denied."}`
![image](https://user-images.githubusercontent.com/33878954/173198927-86a6972a-7121-4c25-95ba-b5e3a277bbe0.png)

Even updating to the latest MCC artifact results the same exact message.
This is due to _appveyor_ deleting the artifacts after 1 whole month.
![image](https://user-images.githubusercontent.com/33878954/173198966-97add29b-8aaf-49df-adb7-bcc4dddaccab.png)

**Comment by Anthony01M** [comment]
Potential Fixes for this situation is to download it from [github releases](https://github.com/MCCTeam/Minecraft-Console-Client/releases)
![image](https://user-images.githubusercontent.com/33878954/173199077-05576744-156c-4210-80b5-c07938c42e6d.png)

**Comment by Anthony01M** [comment]
I'll probably have to rework on the panel itself, potentially adding support to upgrade from the panel itself by changing the link however there's still an issue, which I'm thinking of solving it by making this admin only and for the "customers" they will have a list of available MinecraftConsoleClient.exe buttons or something.

**Comment by BetTD** [comment]
https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest/download/MinecraftClient.exe 👍🏻

**Comment by Anthony01M** [comment]
> https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest/download/MinecraftClient.exe 👍🏻 

We could indeed simply change the link to download the latest from github, however, we believe that some issues may occur later on, which leads us to wanting an administrator "control" over this matter leaving everything in the admins hands, will temporarily push the fix though, in case people want to update to the new version of MCC and open a new issue.
